### ISSUE TITLE
Possible to add toggle command?

### ISSUE THREAD

**Issue by zaydek** [hborchardt/virtual-better-align#1]
This is a really profound plugin, I haven't found anything that works to the same effect.

I was wondering if you could republish this with the addition of a command palette command so it's functionality could be toggled on and off with a shortcut like (like Command-A in https://github.com/chouzz/vscode-better-align/) so it would make it easier to quickly virtual format for legibility and turn off later?

**Comment by hborchardt** [comment]
I'm glad you like it! I added and released a toggle command in a9fe684f9762fae133293e8bbb474c928d7e2c4c, and you can setup a shortcut for it.

**Comment by zaydek** [comment]
Awesome! Thanks so much. 🙂
